@startuml
class Building {
-women: WomenRestroom
-men: MenRestroom
}

class WomenRestroom {
-toilets[2]: Toilet
-accessible: Accessible
+chooseRestroom()
}

class MenRestroom {
-toilets[2]: Toilet
-urinals[4]: Urinal
-accessible: Accessible
+chooseRestroom()
}

class Accessible {
-available: boolean
-toiletPaper: boolean
-openSeatCover: boolean
-openDoor: boolean
+use()
+openDoor()
+closeDoor()
+openSeatCover()
+closeSeatCover()
+pullHandle()
}

class Toilet {
-available: boolean
-toiletPaper: boolean
-openSeatCover: boolean
-openDoor: boolean
+use()
+openDoor()
+closeDoor()
+openSeatCover()
+closeSeatCover()
+pullHandle()
}

class Urinal {
-available: boolean
+use()
+pullHandle()
}
@enduml